import React, { useContext, useEffect, useState, useRef } from 'react';
import { DoctorContext } from '../../context/DoctorContext';
import { AppContext } from '../../context/AppContext';
import { assets } from '../../assets/assets';
import * as XLSX from 'xlsx';

const DoctorAppointments = () => {
  const { dToken, appointments, getAppointments, cancelAppointment, completeAppointment } = useContext(DoctorContext);
  const { slotDateFormat, calculateAge, currency } = useContext(AppContext);

  // State for filters
  const [filteredAppointments, setFilteredAppointments] = useState(appointments);
  const [filters, setFilters] = useState({
    status: 'all',
    payment: '',
    startDate: '',
    endDate: ''
  });

  // Ref for the table to print
  const printRef = useRef(null);

  // Print functionality
  const handlePrint = () => {
    // Use a slightly different approach to ensure it works
    const printContent = document.createElement('div');
    printContent.innerHTML = `
      <html>
        <head>
          <title>Doctor Appointments Report</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              padding: 20px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-bottom: 20px;
            }
            th, td {
              border: 1px solid #ddd;
              padding: 8px;
              text-align: left;
            }
            th {
              background-color: #f2f2f2;
              font-weight: bold;
            }
            .print-header {
              text-align: center;
              margin-bottom: 20px;
            }
            .print-footer {
              margin-top: 20px;
              text-align: center;
              font-size: 10px;
              color: #888;
            }
          </style>
        </head>
        <body>
          <div class="print-header">
            <h1>Doctor Appointments Report</h1>
            <p>Generated on: ${new Date().toLocaleString()}</p>
            ${filters.startDate && filters.endDate ? 
              `<p>Date Range: ${new Date(filters.startDate).toLocaleDateString()} - ${new Date(filters.endDate).toLocaleDateString()}</p>` : 
              ''}
          </div>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Patient</th>
                <th>Phone</th>
                <th>Payment</th>
                <th>Age</th>
                <th>Date & Time</th>
                <th>Fees</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${filteredAppointments.map((item, index) => `
                <tr>
                  <td>${index + 1}</td>
                  <td>${item.userData.name}</td>
                  <td>${item.userData.phone || 'N/A'}</td>
                  <td>${item.payment ? 'Online' : 'CASH'}</td>
                  <td>${calculateAge(item.userData.dob)}</td>
                  <td>${slotDateFormat(item.slotDate)}, ${item.slotTime}</td>
                  <td>${currency}${item.amount}</td>
                  <td>${item.cancelled ? 'Cancelled' : item.isCompleted ? 'Completed' : 'Pending'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="print-footer">
            <p>Total Appointments: ${filteredAppointments.length}</p>
            <p>Generated by MediCareHub Management System</p>
          </div>
        </body>
      </html>
    `;
    
    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    printWindow.document.open();
    printWindow.document.write(printContent.innerHTML);
    printWindow.document.close();
    
    // Wait for content to load then print
    printWindow.onload = function() {
      printWindow.focus();
      printWindow.print();
      printWindow.onafterprint = function() {
        printWindow.close();
      };
    };
    
    // Fallback if onload doesn't trigger
    setTimeout(() => {
      if (printWindow.document) {
        printWindow.focus();
        printWindow.print();
        setTimeout(() => printWindow.close(), 500);
      }
    }, 1000);
  };

  // Export to Excel functionality
  const handleExportExcel = () => {
    const data = filteredAppointments.map((item, index) => ({
      '#': index + 1,
      'Patient Name': item.userData.name,
      'Phone Number': item.userData.phone || 'N/A',
      'Payment Method': item.payment ? 'Online' : 'CASH',
      'Age': calculateAge(item.userData.dob),
      'Date': slotDateFormat(item.slotDate),
      'Time': item.slotTime,
      'Fees': `${currency}${item.amount}`,
      'Status': item.cancelled ? 'Cancelled' : item.isCompleted ? 'Completed' : 'Pending',
    }));

    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Doctor Appointments');
    
    const fileName = filters.startDate && filters.endDate ? 
      `doctor_appointments_${new Date(filters.startDate).toISOString().split('T')[0]}_to_${new Date(filters.endDate).toISOString().split('T')[0]}.xlsx` : 
      'doctor_appointments_report.xlsx';
    
    XLSX.writeFile(workbook, fileName);
  };

  // Completely revised date parsing function that works with your appointment model
  const parseAppointmentDate = (dateStr) => {
    try {
      if (!dateStr) return null;
      
      // First, try using native timestamp if 'date' is available (fallback)
      // Since we know from your schema that slotDate is a string, 
      // but the actual date object is stored in the 'date' field as a number (timestamp)
      
      // Handle DD/MM/YYYY format (which appears to be what slotDateFormat returns)
      if (dateStr.includes('/')) {
        const [day, month, year] = dateStr.split('/').map(Number);
        // Create Date: month is 0-indexed in JavaScript
        return new Date(year, month - 1, day);
      } 
      // Handle YYYY-MM-DD format
      else if (dateStr.includes('-')) {
        // Split and convert to numbers
        const parts = dateStr.split('-').map(Number);
        
        // Check if we have a year-month-day format or day-month-year format
        if (parts[0] > 1000) { // Likely a year
          const [year, month, day] = parts;
          return new Date(year, month - 1, day);
        } else { // Likely day-month-year
          const [day, month, year] = parts;
          return new Date(year, month - 1, day);
        }
      }
      
      // Last resort: try direct parsing
      const parsedDate = new Date(dateStr);
      return isNaN(parsedDate.getTime()) ? null : parsedDate;
    } catch (error) {
      console.error("Error parsing date:", error, dateStr);
      return null;
    }
  };

  // Helper function to get current date in YYYY-MM-DD format
  const formatDateForInput = (date) => {
    const d = new Date(date);
    let month = '' + (d.getMonth() + 1);
    let day = '' + d.getDate();
    const year = d.getFullYear();

    if (month.length < 2) month = '0' + month;
    if (day.length < 2) day = '0' + day;

    return [year, month, day].join('-');
  };

  // Quick filter buttons functionality
  const setQuickDateFilter = (period) => {
    const today = new Date();
    today.setHours(23, 59, 59, 999); // End of today
    
    let startDate = new Date(today);
    
    if (period === 'today') {
      startDate = new Date(today);
      startDate.setHours(0, 0, 0, 0); // Start of today
    } else if (period === 'lastWeek') {
      startDate.setDate(today.getDate() - 7);
      startDate.setHours(0, 0, 0, 0); // Start of day 7 days ago
    } else if (period === 'lastMonth') {
      startDate.setMonth(today.getMonth() - 1);
      startDate.setHours(0, 0, 0, 0); // Start of day 30 days ago
    } else if (period === 'lastYear') {
      startDate.setFullYear(today.getFullYear() - 1);
      startDate.setHours(0, 0, 0, 0); // Start of day 1 year ago
    }
    
    setFilters(prev => ({
      ...prev,
      startDate: formatDateForInput(startDate),
      endDate: formatDateForInput(today)
    }));
  };

  // Filter function
  const applyFilters = () => {
    if (!appointments || appointments.length === 0) {
      setFilteredAppointments([]);
      return;
    }

    console.log("Applying filters:", filters);
    let result = [...appointments]; // Create a copy to avoid mutation

    // Apply status filter
    if (filters.status !== 'all') {
      result = result.filter(item => {
        if (filters.status === 'completed') return item.isCompleted;
        if (filters.status === 'cancelled') return item.cancelled;
        if (filters.status === 'pending') return !item.isCompleted && !item.cancelled;
        return true;
      });
    }

    // Apply payment filter
    if (filters.payment !== '') {
      result = result.filter(item => {
        if (filters.payment === 'online') return item.payment;
        if (filters.payment === 'cash') return !item.payment;
        return true;
      });
    }

    // Apply date range filter if both start and end dates are provided
    if (filters.startDate && filters.endDate) {
      const startDate = new Date(filters.startDate);
      startDate.setHours(0, 0, 0, 0); // Start of the day
      
      const endDate = new Date(filters.endDate);
      endDate.setHours(23, 59, 59, 999); // End of the day
      
      console.log("Date filters - startDate:", startDate, "endDate:", endDate);

      result = result.filter(item => {
        // Try using the timestamp from 'date' field first if available
        let appointmentDate;
        
        if (item.date) {
          // If we have a timestamp (as per your schema), use it directly
          appointmentDate = new Date(item.date);
        } else {
          // Fall back to parsing slotDate
          appointmentDate = parseAppointmentDate(item.slotDate);
        }
        
        // Add logging to debug date parsing
        console.log("Appointment:", item.slotDate, "Parsed date:", appointmentDate, 
                    "Using timestamp:", item.date ? true : false);
        
        // Skip if we couldn't parse the date
        if (!appointmentDate) {
          console.log("Couldn't parse date for:", item.slotDate);
          return true; // Keep items with unparseable dates
        }
        
        // Do the date range comparison
        const isInRange = appointmentDate >= startDate && appointmentDate <= endDate;
        console.log("Is in date range:", isInRange);
        return isInRange;
      });
    }

    console.log("Filtered results:", result.length);
    setFilteredAppointments(result);
  };

  // Reset filters
  const resetAllFilters = () => {
    setFilters({
      status: 'all',
      payment: '',
      startDate: '',
      endDate: ''
    });
  };

  // Apply filters when appointments or filters change
  useEffect(() => {
    applyFilters();
  }, [appointments, filters]);

  // Fetch appointments when token is available
  useEffect(() => {
    if (dToken) {
      getAppointments();
    }
  }, [dToken]);

  return (
    <div className='w-full max-w-6xl m-5'>
      <div className='flex flex-col md:flex-row justify-between items-start md:items-center mb-6'>
        <p className='text-lg font-medium flex items-center gap-2'>
          <svg xmlns="http://www.w3.org/2000/svg" className='w-5 h-5 text-blue-600' fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
          </svg>
          All Appointments {filteredAppointments.length > 0 && `(${filteredAppointments.length})`}
        </p>

        {/* Filtering and Export Section */}
        <div className='flex flex-wrap gap-3 mt-3 md:mt-0'>
          {/* Status Filter */}
          <div className='relative'>
            <select
              value={filters.status}
              onChange={(e) => setFilters(prev => ({ ...prev, status: e.target.value }))}
              className='appearance-none bg-white border border-gray-300 rounded-md pl-3 pr-10 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500'
            >
              <option value="all">All Statuses</option>
              <option value="pending">Pending</option>
              <option value="completed">Completed</option>
              <option value="cancelled">Cancelled</option>
            </select>
            <svg xmlns="http://www.w3.org/2000/svg" className='absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none' fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z" />
            </svg>
          </div>

          {/* Payment Filter */}
          <div className='relative'>
            <select
              value={filters.payment}
              onChange={(e) => setFilters(prev => ({ ...prev, payment: e.target.value }))}
              className='appearance-none bg-white border border-gray-300 rounded-md pl-3 pr-10 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500'
            >
              <option value="">All Payments</option>
              <option value="online">Online</option>
              <option value="cash">Cash</option>
            </select>
            <svg xmlns="http://www.w3.org/2000/svg" className='absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none' fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
          </div>

          {/* Reset Filters Button */}
          <button
            onClick={resetAllFilters}
            className='flex items-center gap-2 bg-gray-200 text-gray-700 px-4 py-2 rounded hover:bg-gray-300 transition-colors'
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            Reset
          </button>

          {/* Print Button */}
          <button
            onClick={handlePrint}
            className='flex items-center gap-2 bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition-colors'
          >
            <svg xmlns="http://www.w3.org/2000/svg" className='w-4 h-4' fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print
          </button>

          {/* Export to Excel Button */}
          <button
            onClick={handleExportExcel}
            className='flex items-center gap-2 bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 transition-colors'
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
            </svg>
            Export Excel
          </button>
        </div>
      </div>

      {/* Date Range Picker Section */}
      <div className='mb-6 bg-gray-50 p-4 rounded-lg border'>
        <h3 className='text-sm font-medium mb-3 flex items-center gap-2'>
          <svg xmlns="http://www.w3.org/2000/svg" className='w-4 h-4 text-blue-600' fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
          Date Range Filter
        </h3>
        <div className='flex flex-wrap gap-3'>
          {/* Date Range Inputs */}
          <div className='flex flex-wrap gap-2 items-center'>
            <div className='flex flex-col'>
              <label className='text-xs text-gray-600 mb-1'>From:</label>
              <input 
                type="date" 
                value={filters.startDate}
                onChange={(e) => setFilters(prev => ({ ...prev, startDate: e.target.value }))}
                className='border border-gray-300 rounded px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500'
              />
            </div>
            <div className='flex flex-col'>
              <label className='text-xs text-gray-600 mb-1'>To:</label>
              <input 
                type="date"
                value={filters.endDate}
                onChange={(e) => setFilters(prev => ({ ...prev, endDate: e.target.value }))}
                className='border border-gray-300 rounded px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500'
              />
            </div>
          </div>
          
          {/* Quick Date Range Buttons */}
          <div className='flex flex-wrap gap-2 items-end'>
            <button 
              onClick={() => setQuickDateFilter('today')}
              className='bg-white border border-gray-300 text-gray-700 px-3 py-1.5 rounded text-sm hover:bg-gray-100 transition-colors'
            >
              Today
            </button>
            <button 
              onClick={() => setQuickDateFilter('lastWeek')}
              className='bg-white border border-gray-300 text-gray-700 px-3 py-1.5 rounded text-sm hover:bg-gray-100 transition-colors'
            >
              Last 7 Days
            </button>
            <button 
              onClick={() => setQuickDateFilter('lastMonth')}
              className='bg-white border border-gray-300 text-gray-700 px-3 py-1.5 rounded text-sm hover:bg-gray-100 transition-colors'
            >
              Last 30 Days
            </button>
            <button 
              onClick={() => setQuickDateFilter('lastYear')}
              className='bg-white border border-gray-300 text-gray-700 px-3 py-1.5 rounded text-sm hover:bg-gray-100 transition-colors'
            >
              Last Year
            </button>
          </div>
        </div>
        {filters.startDate && filters.endDate && (
          <p className='text-xs text-gray-600 mt-2'>
            Showing appointments from {new Date(filters.startDate).toLocaleDateString()} to {new Date(filters.endDate).toLocaleDateString()}
          </p>
        )}
      </div>

      <div className='bg-white border rounded text-sm max-h-[80vh] overflow-y-scroll'>
        <div ref={printRef} className="w-full">
          <div className='max-sm:hidden grid grid-cols-[0.5fr_2fr_1.5fr_1fr_1fr_2.5fr_1fr_1fr] gap-1 py-3 px-6 border-b'>
            <p>#</p>
            <p>Patient</p>
            <p>Phone</p>
            <p>Payment</p>
            <p>Age</p>
            <p>Date & Time</p>
            <p>Fees</p>
            <p>Action</p>
          </div>
          
          {filteredAppointments.length > 0 ? (
            filteredAppointments.map((item, index) => (
              <div className='flex flex-wrap justify-between max-sm:gap-5 max-sm:text-base sm:grid grid-cols-[0.5fr_2fr_1.5fr_1fr_1fr_2.5fr_1fr_1fr] gap-1 items-center text-gray-500 py-3 px-6 border-b hover:bg-gray-50' key={index}>
                <p className='max-sm:hidden'>{index + 1}</p>
                <div className='flex items-center gap-2'>
                  <img src={item.userData.image} className='w-8 h-8 rounded-full object-cover' alt="" /> <p>{item.userData.name}</p>
                </div>
                <p className='max-sm:hidden'>{item.userData.phone || 'N/A'}</p>
                <div>
                  <p className='text-xs inline border border-primary px-2 rounded-full'>
                    {item.payment ? 'Online' : 'CASH'}
                  </p>
                </div>
                <p className='max-sm:hidden'>{calculateAge(item.userData.dob)}</p>
                <p>{slotDateFormat(item.slotDate)}, {item.slotTime}</p>
                <p>{currency}{item.amount}</p>
                {item.cancelled
                  ? <p className='text-red-400 text-xs font-medium'>Cancelled</p>
                  : item.isCompleted
                    ? <p className='text-green-500 text-xs font-medium'>Completed</p>
                    : <div className='flex'>
                        <img onClick={() => cancelAppointment(item._id)} className='w-10 cursor-pointer' src={assets.cancel_icon} alt="" />
                        <img onClick={() => completeAppointment(item._id)} className='w-10 cursor-pointer' src={assets.tick_icon} alt="" />
                      </div>
                }
              </div>
            ))
          ) : (
            <div className='text-center py-10 text-gray-500'>
              <svg xmlns="http://www.w3.org/2000/svg" className='w-16 h-16 mx-auto mb-4 text-gray-300' fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
              </svg>
              <p className='text-xl'>No appointments found matching the current filters.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default DoctorAppointments;