import React, { useEffect, useState, useRef, useContext } from 'react';
import { AdminContext } from '../../context/AdminContext';
import { AppContext } from '../../context/AppContext';
import * as XLSX from 'xlsx';

const AllAppointments = () => {
  const { aToken, appointments, cancelAppointment, getAllAppointments } = useContext(AdminContext);
  const { slotDateFormat, calculateAge, currency } = useContext(AppContext);

  // State for filters
  const [filteredAppointments, setFilteredAppointments] = useState(appointments);
  const [filters, setFilters] = useState({
    status: 'all',
    doctor: '',
    dateRange: '',
  });

  // Ref for the table to print
  const printRef = useRef(null);

  // Get unique doctors for dropdown
  const uniqueDoctors = [...new Set(appointments.map(item => item.docData.name))];

  // Print functionality
  const handlePrint = () => {
    const printWindow = window.open('', '', 'height=500, width=800');
    printWindow.document.write('<html><head><title>Appointments Report</title>');
    printWindow.document.write(`
      <style>
        body { font-family: Arial, sans-serif; }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 20px;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 8px;
          text-align: left;
        }
        th {
          background-color: #f2f2f2;
          font-weight: bold;
        }
        .print-header {
          text-align: center;
          margin-bottom: 20px;
        }
        .print-footer {
          margin-top: 20px;
          text-align: center;
          font-size: 10px;
          color: #888;
        }
      </style>
    `);
    printWindow.document.write('</head><body>');
    printWindow.document.write(`
      <div class="print-header">
        <h1>Appointments Report</h1>
        <p>Generated on: ${new Date().toLocaleString()}</p>
      </div>
    `);

    const tableHTML = `
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Patient</th>
            <th>Age</th>
            <th>Date & Time</th>
            <th>Doctor</th>
            <th>Fees</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${filteredAppointments.map((item, index) => `
            <tr>
              <td>${index + 1}</td>
              <td>${item.userData.name}</td>
              <td>${calculateAge(item.userData.dob)}</td>
              <td>${slotDateFormat(item.slotDate)}, ${item.slotTime}</td>
              <td>${item.docData.name}</td>
              <td>${currency}${item.amount}</td>
              <td>${item.cancelled ? 'Cancelled' : item.isCompleted ? 'Completed' : 'Pending'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    `;

    printWindow.document.write(tableHTML);
    printWindow.document.write(`
      <div class="print-footer">
        <p>Total Appointments: ${filteredAppointments.length}</p>
        <p>Generated by Prescripto Management System</p>
      </div>
    `);

    printWindow.document.write('</body></html>');
    printWindow.document.close();
    printWindow.print();
    printWindow.close();
  };

  // Export to Excel functionality
  const handleExportExcel = () => {
    const data = filteredAppointments.map((item, index) => ({
      '#': index + 1,
      'Patient Name': item.userData.name,
      'Age': calculateAge(item.userData.dob),
      'Date': slotDateFormat(item.slotDate),
      'Time': item.slotTime,
      'Doctor Name': item.docData.name,
      'Fees': `${currency}${item.amount}`,
      'Status': item.cancelled ? 'Cancelled' : item.isCompleted ? 'Completed' : 'Pending',
    }));

    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Appointments');
    XLSX.writeFile(workbook, 'appointments_report.xlsx');
  };

  // Filter function
  const applyFilters = () => {
    let result = appointments;

    if (filters.status !== 'all') {
      result = result.filter(item => {
        if (filters.status === 'completed') return item.isCompleted;
        if (filters.status === 'cancelled') return item.cancelled;
        if (filters.status === 'pending') return !item.isCompleted && !item.cancelled;
        return true;
      });
    }

    if (filters.doctor) {
      result = result.filter(item => item.docData.name === filters.doctor);
    }

    if (filters.dateRange) {
      const today = new Date();
      const oneWeekAgo = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000);
      const oneMonthAgo = new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000);

      result = result.filter(item => {
        const appointmentDate = new Date(item.slotDate);
        if (filters.dateRange === 'lastWeek') return appointmentDate >= oneWeekAgo;
        if (filters.dateRange === 'lastMonth') return appointmentDate >= oneMonthAgo;
        return true;
      });
    }

    setFilteredAppointments(result);
  };

  // Apply filters when appointments or filters change
  useEffect(() => {
    applyFilters();
  }, [appointments, filters]);

  // Fetch appointments when token is available
  useEffect(() => {
    if (aToken) {
      getAllAppointments();
    }
  }, [aToken]);

  return (
    <div className='container mx-auto px-4 py-6'>
      <div className='flex justify-between items-center mb-6'>
        <h1 className='text-2xl font-bold text-gray-800 flex items-center gap-3'>
          <svg xmlns="http://www.w3.org/2000/svg" className='w-6 h-6 text-blue-600' fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
          </svg>
          All Appointments
        </h1>

        {/* Filtering and Export Section */}
        <div className='flex items-center gap-4'>
          {/* Existing Filters */}
          <div className='relative group'>
            <select
              value={filters.status}
              onChange={(e) => setFilters(prev => ({ ...prev, status: e.target.value }))}
              className='appearance-none w-full bg-white border border-gray-300 rounded-md pl-3 pr-10 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500'
            >
              <option value="all">All Statuses</option>
              <option value="pending">Pending</option>
              <option value="completed">Completed</option>
              <option value="cancelled">Cancelled</option>
            </select>
            <svg xmlns="http://www.w3.org/2000/svg" className='absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none' fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z" />
            </svg>
          </div>

          {/* Doctor Filter */}
          <div className='relative group'>
            <select
              value={filters.doctor}
              onChange={(e) => setFilters(prev => ({ ...prev, doctor: e.target.value }))}
              className='appearance-none w-full bg-white border border-gray-300 rounded-md pl-3 pr-10 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500'
            >
              <option value="">All Doctors</option>
              {uniqueDoctors.map((doctor, index) => (
                <option key={index} value={doctor}>{doctor}</option>
              ))}
            </select>
            <svg xmlns="http://www.w3.org/2000/svg" className='absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none' fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>

          {/* Date Range Filter */}
          <div className='relative group'>
            <select
              value={filters.dateRange}
              onChange={(e) => setFilters(prev => ({ ...prev, dateRange: e.target.value }))}
              className='appearance-none w-full bg-white border border-gray-300 rounded-md pl-3 pr-10 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500'
            >
              <option value="">All Dates</option>
              <option value="lastWeek">Last Week</option>
              <option value="lastMonth">Last Month</option>
            </select>
            <svg xmlns="http://www.w3.org/2000/svg" className='absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none' fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
          </div>

          {/* Print Button */}
          <button
            onClick={handlePrint}
            className='flex items-center gap-2 bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition-colors'
          >
            <svg xmlns="http://www.w3.org/2000/svg" className='w-5 h-5' fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print
          </button>

          {/* Export to Excel Button */}
          <button
            onClick={handleExportExcel}
            className='flex items-center gap-2 bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 transition-colors'
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
            </svg>
            Export Excel
          </button>
        </div>
      </div>

      <div className='bg-white shadow-md rounded-lg overflow-hidden'>
        <div className='overflow-x-auto'>
          <table ref={printRef} className='w-full'>
            <thead className='bg-gray-50 border-b'>
              <tr>
                <th className='px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>#</th>
                <th className='px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>Patient</th>
                <th className='px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>Age</th>
                <th className='px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>Date & Time</th>
                <th className='px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>Doctor</th>
                <th className='px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>Fees</th>
                <th className='px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>Status</th>
              </tr>
            </thead>
            <tbody className='divide-y divide-gray-200'>
              {filteredAppointments.map((item, index) => (
                <tr
                  key={item._id}
                  className='hover:bg-gray-50 transition-colors duration-200'
                >
                  <td className='px-4 py-4 whitespace-nowrap text-sm text-gray-500'>{index + 1}</td>
                  <td className='px-4 py-4 whitespace-nowrap'>
                    <div className='flex items-center'>
                      <img
                        src={item.userData.image}
                        alt={item.userData.name}
                        className='h-10 w-10 rounded-full mr-3 object-cover'
                      />
                      <div>
                        <div className='text-sm font-medium text-gray-900'>{item.userData.name}</div>
                      </div>
                    </div>
                  </td>
                  <td className='px-4 py-4 whitespace-nowrap text-sm text-gray-500'>
                    {calculateAge(item.userData.dob)}
                  </td>
                  <td className='px-4 py-4 whitespace-nowrap text-sm text-gray-500'>
                    {slotDateFormat(item.slotDate)}, {item.slotTime}
                  </td>
                  <td className='px-4 py-4 whitespace-nowrap'>
                    <div className='flex items-center'>
                      <img
                        src={item.docData.image}
                        alt={item.docData.name}
                        className='h-10 w-10 rounded-full mr-3 object-cover bg-gray-200'
                      />
                      <div className='text-sm font-medium text-gray-900'>{item.docData.name}</div>
                    </div>
                  </td>
                  <td className='px-4 py-4 whitespace-nowrap text-sm text-gray-500'>
                    {currency}{item.amount}
                  </td>
                  <td className='px-4 py-4 whitespace-nowrap'>
                    {item.cancelled ? (
                      <span className='inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800'>
                        Cancelled
                      </span>
                    ) : item.isCompleted ? (
                      <span className='inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800'>
                        Completed
                      </span>
                    ) : (
                      <button
                        onClick={() => cancelAppointment(item._id)}
                        className='text-red-600 hover:text-red-900 inline-flex items-center'
                      >
                        Cancel
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* No results message */}
          {filteredAppointments.length === 0 && (
            <div className='text-center py-10 text-gray-500'>
              <svg xmlns="http://www.w3.org/2000/svg" className='w-16 h-16 mx-auto mb-4 text-gray-300' fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
              </svg>
              <p className='text-xl'>No appointments found matching the current filters.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AllAppointments;

